### ISSUE TITLE
Save order safety

### ISSUE THREAD

**Issue by muccy** [zuvola/tiny_storage#1]
Hi, first of all great work on a tiny but big idea :)
Reading docs and code — I'm not an isolates expert — I can't understand for sure that saving order is ensured.

If I set `{ "A": 1, "B": 1}` and I immediately (without awaiting) set `{ "A": 2, "B": 1 }` I would expect to have saved  `{ "A": 2, "B": 1 }` to disk. Is it the case? Is there a sort of queue of pending saves?

Thanks a lot

**Comment by zuvola** [comment]
In tiny_storage, Microtask is used to ensure that only one write operation is performed in the same event loop.
No matter how many times 'set' is called, the last state is saved, so the order is guaranteed even though no queue is used.

```dart
storage.set('key_1', 'val_1');
// No write operation is called.
storage.set('key_1', 'val_2');
// No write operation is called.
storage.set('key_1', 'val_3');
// The write operation is called at this timing.
await Future.delayed(Duration.zero);
```

**Comment by muccy** [comment]
And because they are implicitly queued, it means that the order is guaranteed even between event loops (say because of a long write operation), isn't it?

I mean, say there is "Save A" in progress and user triggers a "Save B", "Save B" won't start as long as "Save A" is not complete. So "Save B" data will be saved on disk eventually.

**Comment by zuvola** [comment]
You are right.
The behavior during the save process is also taken into account.
The details are in the run method of the _FlushTask class.

https://github.com/zuvola/tiny_storage/blob/d9998d70b0ad6ec9e11c2f38899d7c76c68d89dd/lib/tiny_storage.dart#L61-L78

The tests are as follows.
https://github.com/zuvola/tiny_storage/blob/d9998d70b0ad6ec9e11c2f38899d7c76c68d89dd/test/tiny_storage_test.dart#L45-L58

**Comment by muccy** [comment]
Cool. If I were you, I'd highlight this behaviour in the README.
Thanks a lot :)
